name: Deploy bot on server
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup docker compose
        uses: docker/setup-compose-action@v1
      - name: Build docker image
        run: docker compose build

      - name: Deploy to server using SSH
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER_NAME }}
          password: ${{ secrets.PASSWORD }}
          script: |
            cd ${{ secrets.PROJECT_PATH }}
            ls -a
            sudo docker stop flask_app
            sudo git pull origin main
            sudo docker compose build
            sudo docker compose up -d
            sudo docker system prune -f
